[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/_next/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/form/:slug"
  to = "/form/:slug"
  status = 200
  force = true